// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.business-approval@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const BUSINESS_APPROVAL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const BUSINESS_APPROVAL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_business_approval { () => { "{\"capability_id\":\"lenso.business-approval@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"cancel\",\"decide\",\"expire\",\"read\",\"request\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_business_approval_client { () => { "{\"capability_id\":\"lenso.business-approval@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_business_approval_client { () => { "{\"capability_id\":\"lenso.business-approval@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CANCEL_OPERATION: &str = "cancel";
pub const DECIDE_OPERATION: &str = "decide";
pub const EXPIRE_OPERATION: &str = "expire";
pub const READ_OPERATION: &str = "read";
pub const REQUEST_OPERATION: &str = "request";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelRequest {
    #[serde(rename = "cancelled_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cancelled_by: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CancelResponse {
    #[serde(rename = "evidence_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_ref: Option<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CancelResponseStatus,
    #[serde(rename = "terminal_actor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_actor: Option<String>,
    #[serde(rename = "terminal_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_at: Timestamp,
    #[serde(rename = "terminal_caller_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_caller_instance: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CancelResponseStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CancelError {
    AlreadyTerminal,
    Forbidden,
    InvalidRequest,
    NotRequester,
    RequestNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DecideRequest {
    #[serde(rename = "decided_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decided_by: String,
    #[serde(rename = "decision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision: DecideRequestDecision,
    #[serde(rename = "evidence_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_ref: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DecideRequestDecision {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DecideResponse {
    #[serde(rename = "evidence_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_ref: Option<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: DecideResponseStatus,
    #[serde(rename = "terminal_actor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_actor: Option<String>,
    #[serde(rename = "terminal_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_at: Timestamp,
    #[serde(rename = "terminal_caller_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_caller_instance: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DecideResponseStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DecideError {
    AlreadyTerminal,
    Forbidden,
    InvalidRequest,
    RequestNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireRequest {
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExpireResponse {
    #[serde(rename = "evidence_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_ref: Option<String>,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ExpireResponseStatus,
    #[serde(rename = "terminal_actor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_actor: Option<String>,
    #[serde(rename = "terminal_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_at: Timestamp,
    #[serde(rename = "terminal_caller_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_caller_instance: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ExpireResponseStatus {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExpireError {
    AlreadyTerminal,
    Forbidden,
    InvalidRequest,
    NotDue,
    RequestNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "approval_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub approval_kind: String,
    #[serde(rename = "evidence_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub evidence_ref: Option<String>,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requested_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_at: Timestamp,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "requester_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_instance: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ReadResponseStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: ReadResponseSubject,
    #[serde(rename = "terminal_actor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_actor: Option<String>,
    #[serde(rename = "terminal_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_at: Option<Timestamp>,
    #[serde(rename = "terminal_caller_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub terminal_caller_instance: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponseSubject {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    Forbidden,
    InvalidRequest,
    RequestNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestRequest {
    #[serde(rename = "approval_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub approval_kind: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requested_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requested_by: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: RequestRequestSubject,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestRequestSubject {
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RequestResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RequestResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RequestResponseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct BusinessApprovalCancel;
impl RequestCapability for BusinessApprovalCancel {
    type Request = CancelRequest;
    type Response = CancelResponse;
    type DomainError = CancelError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CANCEL_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BusinessApprovalRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).cancel(context, request)
    }
}

#[derive(Debug)]
pub struct BusinessApprovalDecide;
impl RequestCapability for BusinessApprovalDecide {
    type Request = DecideRequest;
    type Response = DecideResponse;
    type DomainError = DecideError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DECIDE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BusinessApprovalRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).decide(context, request)
    }
}

#[derive(Debug)]
pub struct BusinessApprovalExpire;
impl RequestCapability for BusinessApprovalExpire {
    type Request = ExpireRequest;
    type Response = ExpireResponse;
    type DomainError = ExpireError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXPIRE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BusinessApprovalRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).expire(context, request)
    }
}

#[derive(Debug)]
pub struct BusinessApprovalRead;
impl RequestCapability for BusinessApprovalRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BusinessApprovalRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

#[derive(Debug)]
pub struct BusinessApprovalRequest;
impl RequestCapability for BusinessApprovalRequest {
    type Request = RequestRequest;
    type Response = RequestResponse;
    type DomainError = RequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<BusinessApprovalRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).request(context, request)
    }
}

impl serde::Serialize for CancelError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyTerminal => serializer.serialize_str("already_terminal"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotRequester => serializer.serialize_str("not_requester"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CancelError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_terminal" => Ok(Self::AlreadyTerminal),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_requester" => Ok(Self::NotRequester),
                "request_not_found" => Ok(Self::RequestNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DecideError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyTerminal => serializer.serialize_str("already_terminal"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DecideError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_terminal" => Ok(Self::AlreadyTerminal),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "request_not_found" => Ok(Self::RequestNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExpireError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadyTerminal => serializer.serialize_str("already_terminal"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotDue => serializer.serialize_str("not_due"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExpireError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_terminal" => Ok(Self::AlreadyTerminal),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_due" => Ok(Self::NotDue),
                "request_not_found" => Ok(Self::RequestNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "request_not_found" => Ok(Self::RequestNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_cancel_request(value: &CancelRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_request(wire: &str) -> Result<CancelRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_cancel_response(value: &CancelResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_response(wire: &str) -> Result<CancelResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_cancel_error(value: &CancelError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_cancel_error(wire: &str) -> Result<CancelError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_decide_request(value: &DecideRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_request(wire: &str) -> Result<DecideRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_decide_response(value: &DecideResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_response(wire: &str) -> Result<DecideResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_decide_error(value: &DecideError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_error(wire: &str) -> Result<DecideError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_expire_request(value: &ExpireRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_request(wire: &str) -> Result<ExpireRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_response(value: &ExpireResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_response(wire: &str) -> Result<ExpireResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_expire_error(value: &ExpireError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_expire_error(wire: &str) -> Result<ExpireError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_request_request(value: &RequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_request(wire: &str) -> Result<RequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_request_response(value: &RequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_response(wire: &str) -> Result<RequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_request_error(value: &RequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_request_error(wire: &str) -> Result<RequestError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoBusinessApprovalCancelResult {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure>;
}
impl __LensoIntoBusinessApprovalCancelResult for Result<CancelResponse, CancelError> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBusinessApprovalCancelResult for Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> { self }
}
impl __LensoIntoBusinessApprovalCancelResult for Result<CancelResponse, lenso_plugin_authoring::PluginError<CancelError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBusinessApprovalCancelResult for Result<CancelResponse, BusinessApprovalCancelInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CancelResponse, CancelError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BusinessApprovalCancelInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BusinessApprovalCancelInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoBusinessApprovalDecideResult {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure>;
}
impl __LensoIntoBusinessApprovalDecideResult for Result<DecideResponse, DecideError> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBusinessApprovalDecideResult for Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> { self }
}
impl __LensoIntoBusinessApprovalDecideResult for Result<DecideResponse, lenso_plugin_authoring::PluginError<DecideError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBusinessApprovalDecideResult for Result<DecideResponse, BusinessApprovalDecideInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BusinessApprovalDecideInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BusinessApprovalDecideInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoBusinessApprovalExpireResult {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure>;
}
impl __LensoIntoBusinessApprovalExpireResult for Result<ExpireResponse, ExpireError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBusinessApprovalExpireResult for Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> { self }
}
impl __LensoIntoBusinessApprovalExpireResult for Result<ExpireResponse, lenso_plugin_authoring::PluginError<ExpireError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBusinessApprovalExpireResult for Result<ExpireResponse, BusinessApprovalExpireInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExpireResponse, ExpireError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BusinessApprovalExpireInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BusinessApprovalExpireInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoBusinessApprovalReadResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure>;
}
impl __LensoIntoBusinessApprovalReadResult for Result<ReadResponse, ReadError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBusinessApprovalReadResult for Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> { self }
}
impl __LensoIntoBusinessApprovalReadResult for Result<ReadResponse, lenso_plugin_authoring::PluginError<ReadError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBusinessApprovalReadResult for Result<ReadResponse, BusinessApprovalReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResponse, ReadError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BusinessApprovalReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BusinessApprovalReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoBusinessApprovalRequestResult {
    fn __lenso_into_result(self) -> Result<Result<RequestResponse, RequestError>, RuntimeFailure>;
}
impl __LensoIntoBusinessApprovalRequestResult for Result<RequestResponse, RequestError> {
    fn __lenso_into_result(self) -> Result<Result<RequestResponse, RequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoBusinessApprovalRequestResult for Result<Result<RequestResponse, RequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RequestResponse, RequestError>, RuntimeFailure> { self }
}
impl __LensoIntoBusinessApprovalRequestResult for Result<RequestResponse, lenso_plugin_authoring::PluginError<RequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RequestResponse, RequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoBusinessApprovalRequestResult for Result<RequestResponse, BusinessApprovalRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RequestResponse, RequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(BusinessApprovalRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(BusinessApprovalRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait BusinessApprovalProvider: fmt::Debug + 'static {
    fn cancel(&self, context: InvocationContext, request: CancelRequest) -> NativeRequestFuture<BusinessApprovalCancel>;
    fn decide(&self, context: InvocationContext, request: DecideRequest) -> NativeRequestFuture<BusinessApprovalDecide>;
    fn expire(&self, context: InvocationContext, request: ExpireRequest) -> NativeRequestFuture<BusinessApprovalExpire>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<BusinessApprovalRead>;
    fn request(&self, context: InvocationContext, request: RequestRequest) -> NativeRequestFuture<BusinessApprovalRequest>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_business_approval {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportBusinessApproval;
        impl $crate::BusinessApprovalProvider for $plugin {
        fn cancel(&self, context: __LensoNativeSupportBusinessApproval::InvocationContext, request: $crate::CancelRequest) -> __LensoNativeSupportBusinessApproval::NativeRequestFuture<$crate::BusinessApprovalCancel> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::cancel(&plugin, context, request).await;
                $crate::__LensoIntoBusinessApprovalCancelResult::__lenso_into_result(result)
            })
        }
        fn decide(&self, context: __LensoNativeSupportBusinessApproval::InvocationContext, request: $crate::DecideRequest) -> __LensoNativeSupportBusinessApproval::NativeRequestFuture<$crate::BusinessApprovalDecide> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::decide(&plugin, context, request).await;
                $crate::__LensoIntoBusinessApprovalDecideResult::__lenso_into_result(result)
            })
        }
        fn expire(&self, context: __LensoNativeSupportBusinessApproval::InvocationContext, request: $crate::ExpireRequest) -> __LensoNativeSupportBusinessApproval::NativeRequestFuture<$crate::BusinessApprovalExpire> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::expire(&plugin, context, request).await;
                $crate::__LensoIntoBusinessApprovalExpireResult::__lenso_into_result(result)
            })
        }
        fn read(&self, context: __LensoNativeSupportBusinessApproval::InvocationContext, request: $crate::ReadRequest) -> __LensoNativeSupportBusinessApproval::NativeRequestFuture<$crate::BusinessApprovalRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read(&plugin, context, request).await;
                $crate::__LensoIntoBusinessApprovalReadResult::__lenso_into_result(result)
            })
        }
        fn request(&self, context: __LensoNativeSupportBusinessApproval::InvocationContext, request: $crate::RequestRequest) -> __LensoNativeSupportBusinessApproval::NativeRequestFuture<$crate::BusinessApprovalRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::request(&plugin, context, request).await;
                $crate::__LensoIntoBusinessApprovalRequestResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct BusinessApprovalRequestEndpoint { provider: Rc<dyn BusinessApprovalProvider> }

#[derive(Debug)]
pub struct BusinessApprovalEndpoint<P: BusinessApprovalProvider> { provider: Rc<P>, request_endpoint: BusinessApprovalRequestEndpoint }
impl<P: BusinessApprovalProvider> BusinessApprovalEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn BusinessApprovalProvider> = provider.clone();
        Self { provider, request_endpoint: BusinessApprovalRequestEndpoint { provider: request_provider } }
    }
}

impl<P: BusinessApprovalProvider> NativeRequestEndpoint for BusinessApprovalEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CANCEL_OPERATION,
        DECIDE_OPERATION,
        EXPIRE_OPERATION,
        READ_OPERATION,
        REQUEST_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CANCEL_OPERATION => {
                let Ok(request) = request.downcast::<CancelRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).cancel(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            DECIDE_OPERATION => {
                let Ok(request) = request.downcast::<DecideRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).decide(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXPIRE_OPERATION => {
                let Ok(request) = request.downcast::<ExpireRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).expire(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<RequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_business_approval {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::BusinessApprovalEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_business_approval {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_business_approval!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct BusinessApprovalClient {
    cancel: NativeRequestHandle<BusinessApprovalCancel>,
    decide: NativeRequestHandle<BusinessApprovalDecide>,
    expire: NativeRequestHandle<BusinessApprovalExpire>,
    read: NativeRequestHandle<BusinessApprovalRead>,
    request: NativeRequestHandle<BusinessApprovalRequest>,
}
impl BusinessApprovalClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn cancel(&self, request: CancelRequest) -> Result<CancelResponse, BusinessApprovalCancelInvocationError> {
        self.cancel.invoke(CANCEL_OPERATION, request).await
            .map_err(BusinessApprovalCancelInvocationError::Runtime)?
            .map_err(BusinessApprovalCancelInvocationError::Domain)
    }

    pub async fn cancel_with_context(&self, context: InvocationContext, request: CancelRequest) -> Result<CancelResponse, BusinessApprovalCancelInvocationError> {
        self.cancel.invoke_with_context(CANCEL_OPERATION, context, request).await
            .map_err(BusinessApprovalCancelInvocationError::Runtime)?
            .map_err(BusinessApprovalCancelInvocationError::Domain)
    }

    pub async fn decide(&self, request: DecideRequest) -> Result<DecideResponse, BusinessApprovalDecideInvocationError> {
        self.decide.invoke(DECIDE_OPERATION, request).await
            .map_err(BusinessApprovalDecideInvocationError::Runtime)?
            .map_err(BusinessApprovalDecideInvocationError::Domain)
    }

    pub async fn decide_with_context(&self, context: InvocationContext, request: DecideRequest) -> Result<DecideResponse, BusinessApprovalDecideInvocationError> {
        self.decide.invoke_with_context(DECIDE_OPERATION, context, request).await
            .map_err(BusinessApprovalDecideInvocationError::Runtime)?
            .map_err(BusinessApprovalDecideInvocationError::Domain)
    }

    pub async fn expire(&self, request: ExpireRequest) -> Result<ExpireResponse, BusinessApprovalExpireInvocationError> {
        self.expire.invoke(EXPIRE_OPERATION, request).await
            .map_err(BusinessApprovalExpireInvocationError::Runtime)?
            .map_err(BusinessApprovalExpireInvocationError::Domain)
    }

    pub async fn expire_with_context(&self, context: InvocationContext, request: ExpireRequest) -> Result<ExpireResponse, BusinessApprovalExpireInvocationError> {
        self.expire.invoke_with_context(EXPIRE_OPERATION, context, request).await
            .map_err(BusinessApprovalExpireInvocationError::Runtime)?
            .map_err(BusinessApprovalExpireInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, BusinessApprovalReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(BusinessApprovalReadInvocationError::Runtime)?
            .map_err(BusinessApprovalReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, BusinessApprovalReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(BusinessApprovalReadInvocationError::Runtime)?
            .map_err(BusinessApprovalReadInvocationError::Domain)
    }

    pub async fn request(&self, request: RequestRequest) -> Result<RequestResponse, BusinessApprovalRequestInvocationError> {
        self.request.invoke(REQUEST_OPERATION, request).await
            .map_err(BusinessApprovalRequestInvocationError::Runtime)?
            .map_err(BusinessApprovalRequestInvocationError::Domain)
    }

    pub async fn request_with_context(&self, context: InvocationContext, request: RequestRequest) -> Result<RequestResponse, BusinessApprovalRequestInvocationError> {
        self.request.invoke_with_context(REQUEST_OPERATION, context, request).await
            .map_err(BusinessApprovalRequestInvocationError::Runtime)?
            .map_err(BusinessApprovalRequestInvocationError::Domain)
    }
}

impl CapabilityClient for BusinessApprovalClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            cancel: dependencies.one::<BusinessApprovalCancel>()?,
            decide: dependencies.one::<BusinessApprovalDecide>()?,
            expire: dependencies.one::<BusinessApprovalExpire>()?,
            read: dependencies.one::<BusinessApprovalRead>()?,
            request: dependencies.one::<BusinessApprovalRequest>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for BusinessApprovalClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    cancel: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BusinessApprovalCancel>()?,
                    decide: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BusinessApprovalDecide>()?,
                    expire: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BusinessApprovalExpire>()?,
                    read: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BusinessApprovalRead>()?,
                    request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<BusinessApprovalRequest>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum BusinessApprovalCancelInvocationError {
    Domain(CancelError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum BusinessApprovalDecideInvocationError {
    Domain(DecideError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum BusinessApprovalExpireInvocationError {
    Domain(ExpireError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum BusinessApprovalReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum BusinessApprovalRequestInvocationError {
    Domain(RequestError),
    Runtime(RuntimeFailure),
}
