import test from "node:test";
import assert from "node:assert/strict";
import {create,setup} from "../src/host_facilities/store.mjs";
import {database,scope} from "./d1-fixture.mjs";
const input=(id="op1",key="key1",requester="management/default")=>({expires_us:"4102444800000000",intent:{request_id:id,requester_instance:requester,idempotency_key:key,requested_by:"alice",approval_kind:"management.write",subject_kind:"management-operation",subject_id:id,intent_digest:"a".repeat(64),requested_at:"2026-09-30T01:02:03Z",expires_at:"2100-01-01T00:00:00Z"}});
const decision=id=>({id,status:"approved",caller:"management/default",actor:"bob",evidence:"human/decision",reason:null});
test("operator setup only; idempotent request and immutable caller/intent persist",async()=>{const db=database(),store=create(db,scope(),{profile:"workers-d1"});await assert.rejects(store.readiness());assert.equal(db.calls.batches,0);await setup(db);await store.readiness();const first=await store.request(input());assert.equal(first.created,true);const replay=await store.request(input());assert.equal(replay.created,false);assert.deepEqual(replay.rows,first.rows);assert.equal(await store.read({id:"op1",requester:"other/default"}),null);const conflict=await store.request(input("other-op","key1"));assert.equal(conflict.created,false);assert.equal(conflict.rows[0].request_id,"op1");assert.ok(db.calls.sessions.every(s=>s==="first-primary"));db.close();});
test("lost decision reply durable terminal CAS never repeats and scoped cancellation/expiry remain pending-only",async()=>{const db=database();await setup(db);let store=create(db,scope(),{profile:"workers-d1"});await store.request(input());db.calls.failAfterCommit=true;await assert.rejects(store.decide(decision("op1")),/lost_reply/);store=create(db,scope(),{profile:"workers-d1"});const persisted=await store.read({id:"op1",requester:null});assert.equal(persisted.status,"approved");assert.equal(persisted.revision,2);assert.equal(persisted.terminal_actor,"bob");assert.equal(persisted.intent_digest,"a".repeat(64));const again=await store.decide({...decision("op1"),actor:"mallory"});assert.equal(again.changed,false);assert.deepEqual(again.approval,persisted);await store.request(input("op2","key2"));assert.equal((await store.cancel({id:"op2",caller:"other/default",actor:"eve",reason:null})).changed,false);assert.equal((await store.expire({id:"op2",caller:"expire/default"})).changed,false);assert.equal((await store.cancel({id:"op2",caller:"management/default",actor:"alice",reason:null})).approval.status,"cancelled");const due=input("op3","key3");due.expires_us="1";await store.request(due);const expired=await store.expire({id:"op3",caller:"expire/default"});assert.equal(expired.changed,true);assert.equal(expired.approval.revision,2);assert.equal(expired.approval.terminal_actor,null);db.close();});

test("wrong profile and an incompatible ledger fail before migration",async()=>{const db=database();assert.throws(()=>create(db,scope(),{profile:"native-pg"}));await setup(db);const session=db.withSession("first-primary");await session.batch([session.prepare("UPDATE lenso_approval_schema SET version=99 WHERE singleton=1")]);const before=db.calls.batches;await assert.rejects(setup(db),/incompatible/);assert.equal(db.calls.batches,before);db.close();});

test("malformed transition receipt never becomes a known domain refusal",async()=>{const db=database();await setup(db);const store=create(db,scope(),{profile:"workers-d1"});await store.request(input());db.calls.malformedAfterCommit=true;await assert.rejects(store.decide(decision("op1")),/receipt_unknown/);const persisted=await store.read({id:"op1",requester:null});assert.equal(persisted.status,"approved");assert.equal(persisted.revision,2);assert.equal(persisted.terminal_actor,"bob");assert.equal(db.calls.batches,3);db.close();});

test("setup refuses an existing unowned aggregate instead of silently adopting it",async()=>{const db=database(),session=db.withSession("first-primary");await session.batch([session.prepare("CREATE TABLE business_approval_requests(foreign_id TEXT)")]);const before=db.calls.batches;await assert.rejects(setup(db),/schema_unmanaged/);assert.equal(db.calls.batches,before);db.close();});

test("a fresh read after an approval wait observes the concurrent terminal decision",async()=>{
 let status="pending",sessions=0;
 const db={withSession(mode){assert.equal(mode,"first-primary");sessions++;const snapshot=status;return {prepare(sql){return {bind(){return this;},async first(){return sql.includes("lenso_approval_schema")?{version:1}:{record_json:JSON.stringify({status:snapshot})};}};}};}};
 const store=create(db,scope(),{profile:"workers-d1"});
 await store.readiness();assert.equal((await store.read({id:"op1",requester:null})).status,"pending");
 status="approved";
 assert.equal((await store.read({id:"op1",requester:null})).status,"approved");assert.equal(sessions,3);
});
